### ISSUE TITLE
Exception running with python 3.7

### ISSUE THREAD

**Issue by HyperTesto** [apm1467/videocr#3] opened 2019-07-14 14:37 UTC
Hello,
i was trying to run videocr on a test avi file but i ran into this issue:

```
$ python3.7 test.py 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 470, in _handle_results
    task = get()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() takes 1 positional argument but 2 were given
```

I'm not a python guy so i don't know where and how to get more information about this.
Thank you, this library look very promising!

**Comment by apm1467** [comment] 2019-07-14 14:41
Thank you for trying! May I see the content of test.py? And which OS do you use?

**Comment by HyperTesto** [comment] 2019-07-14 14:45
This is the file content:

```python
# print_sub.py

import videocr

if __name__ == '__main__':
    print(videocr.get_subtitles("test.avi", lang='ita', sim_threshold=70, conf_threshold=65))
```

And this is my OS information:

```
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
```

**Comment by apm1467** [comment] 2019-07-14 15:13
I will run a Linux Mint virtual machine and try to reproduce the bug. 

In the mean time, could you convert the video into mp4 format using ffmpeg and try it again?

E.g. `$ ffmpeg -i test.avi test.mp4` and then use `test.mp4` in `print_sub.py`. I would like to see if this is a video format problem.

**Comment by HyperTesto** [comment] 2019-07-14 15:41
Tried, same result T_T.

**Comment by QuinnZhao** [comment] 2019-08-21 04:58
Hi, HyperTesto,

 I have found the same exception when I tried the Videoocr, and I have tried my best to fix this bug.
When I went through the video.py in the lib->site_packages->videocr, I found that
    def __init__(self, path: str):
        self.path = path
        v = cv2.VideoCapture(path)
        if not v.isOpened():
            raise IOError('can not open video format {}'.format(path))
        **self.num_frames = v = cv2.VideoCapture(path)**

the statement which marked bold is the real issue, because self.num_frames was not an int value.
when I changed it to 
self.num_frames = int(v.get(cv2.CAP_PROP_FRAME_COUNT))
the issue we fixed.

**Comment by QuinnZhao** [comment] 2019-08-21 04:59
Hi, HyperTesto,

I have found the same exception when I tried the Videoocr, and I have tried my best to fix this bug.
When I went through the video.py in the lib->site_packages->videocr, I found that
def init(self, path: str):
self.path = path
v = cv2.VideoCapture(path)
if not v.isOpened():
raise IOError('can not open video format {}'.format(path))
self.num_frames = v = cv2.VideoCapture(path)

the statement which marked bold is the real issue, because self.num_frames was not an int value.
when I changed it to
self.num_frames = int(v.get(cv2.CAP_PROP_FRAME_COUNT))
the issue was fixed.

**Comment by QuinnZhao** [comment] 2019-08-21 04:59
Hi, HyperTesto,

I have found the same exception when I tried the Videoocr, and I have tried my best to fix this bug.
When I went through the video.py in the lib->site_packages->videocr, I found that
def init(self, path: str):
self.path = path
v = cv2.VideoCapture(path)
if not v.isOpened():
raise IOError('can not open video format {}'.format(path))
**self.num_frames = v = cv2.VideoCapture(path)**

the statement which marked bold is the real issue, because self.num_frames was not an int value.
when I changed it to
self.num_frames = int(v.get(cv2.CAP_PROP_FRAME_COUNT))
the issue was fixed.

**Comment by husxwy** [comment] 2019-08-24 21:21
python3 shipinzimu.py
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 470, in _handle_results
    task = get()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() takes 1 positional argument but 2 were given

--------
python3 -V
Python 3.7.4
--------
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G87

**Comment by sandmars** [comment] 2019-11-06 13:37
我也遇到同样的错误，我用的是MP4格式的视频。另外，国内是否是必须要梯子才可以用，我发现不挂梯子连接不了

**Comment by zhenzhenwangdd01** [comment] 2019-11-12 01:48
需要安装Tesseract，安装方法 https://github.com/tesseract-ocr/tesseract/wiki

**Comment by udaykumar1506** [comment] 2019-11-13 07:30
@apm1467 Any update on this issue, I am facing the same
Python version -- 3.7.4
Tesseract version -- 3.04.01

**Comment by apm1467** [comment] 2019-12-15 15:11
The problem is now fixed.

Some exception occurred when applying OCR to video frames. Since the OCR runs in a multiprocessing pool, the exception was muted locally in the worker process and the user couldn't get any useful error message.

Now the actual exception message will be printed to stderr. It is likely a Tesseract installation error.

Sorry for my late reply. Please try the new version 0.1.6:
```
$ pip3 install -U videocr
```

**Closed** 2020-01-03 06:57 UTC

**Comment by HyperTesto** [comment] 2020-01-21 22:06
Hi, i missed the notification on this... I'll try out in the next days. Thanks a lot!
